algoritmo "ConteAte10"
// Função :
// Autor :
// Data : 12/01/2022
// Seção de Declarações 
var
   contador, N, Intervalo: inteiro
inicio
      Escreva (" Quer contar até quanto: ")
      Leia (N)
      Escreva (" Qual o intervalo ")
      Leia (Intervalo)
      contador <- 0
      Enquanto (contador <=N) faca
               EscrevaL (contador)
               contador <- contador + intervalo
      FimEnquanto
      EscrevaL (" Terminei de contar ")
fimalgoritmo
